apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: aocs
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    isDefault: true
    editable: true

  - name: SCOE-API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://host.docker.internal:8080/api
    jsonData:
      tlsSkipVerify: true
    editable: true


